SSAGESLabs/PySAGES

pysages/backends/core.py, pysages/backends/hoomd.py
Wrapping the data into JAX's DeviceArrays should be handled by each pysages's backend given the differences in how data is exposed from MD engine to MD engine.
=> Wrap the simulation data from within each backend

pysages/__init__.py, pysages/backends/__init__.py, pysages/backends/api.py, pysages/backends/core.py
Since the backend gets assigned to a global constant within the `backends` module.
=> API clean up: Do not require passing the backend

pysages/ssages/methods/core.py
Before this, `generalize` tried to jit the `update` methods with no option to prevent this. Sometimes, we would like some flexibility for jitting only part of the update code, e.g. if we need to raise an exception.
=> More flexibility for jitting `update` methods

Dockerfile
The docker file includes both a hoomd-blue and openmm installation.
With their respective plugins to interact with pysages.
It does not support GPUs yet, but maybe we can include that in a way.
=> Include a docker file

pysages/backends/hoomd.py
We will keep all created samplers around unless they are detached from the corresponding contexts.
=> [HOOMD] Add a global pool of Sampler objects

pysages/grids.py, tests/test_grids.py
Do note that this is now in `pysages/grids.py` instead of `pysages/ssages/grid.py` (the `ssages` path does not serve any real purpose and I plan to eliminate it eventually).
Once this is merged, I will make another PR switching all the grids-dependent code to use the new API.
=> Rewrite grids API

.github/workflows/ci.yml, pysages/ml/objectives.py, pysages/ml/utils.py, tests/test_ml.py
In more recent versions of jax the `pack` method in `ml/utils.py` will fail to jit compile and needs to be made compatible with jax's [omnistaging](https://github.com/google/jax/blob/main/design_notes/omnistaging.md).
This fixes such issue.
=> Make ml compatible with jax's omistaging

pysages/methods/core.py, pysages/methods/umbrella_integration.py
This is a stopgap solution to enable building FES for methods such as ABF, but I'm exposing the all `ContextWrapper`s generated in all of our current methods.
This is most likely to change in light of #54, but lets move on with this for now.
=> Make the context part of the method

pysages/collective_variables/coordinates.py, pysages/collective_variables/core.py
Closes #105
If a user know this is not necessary, it's easy to set it to `False` after the CV is declared but before the sampling method is built.
=> [CVs] Make `requires_box_unwrapping` true by default

pysages/utils.py, setup.cfg
Also, set minimum lower bound for jax to 0.3.5 to make sure new installations work properly.
=> Update copy to match new jax behavior

.github/workflows/docker-ci.yml
I learned, that having larger files around for longer can be expensive.
We don't pay for it as open-source, but better to limit it anyways.
=> Retention of artifacts

Dockerfile, examples/hoomd-blue/Butane_ANN.ipynb, examples/hoomd-blue/Butane_ANN.md, examples/hoomd-blue/Butane_FUNN.ipynb, examples/hoomd-blue/Butane_FUNN.md, examples/hoomd-blue/Harmonic_Bias.ipynb, examples/hoomd-blue/Harmonic_Bias.md, examples/hoomd-blue/Umbrella_Integration.ipynb, examples/hoomd-blue/Umbrella_Integration.md, examples/openmm/Harmonic_Bias.ipynb, examples/openmm/Harmonic_Bias.md, examples/openmm/metad/Metadynamics-ADP.ipynb, examples/openmm/metad/Metadynamics-ADP.md
The URL for installing jax recently changed. Updating it at all the relevant places here,
=> Update jax installation instructions

.github/workflows/docker-ci.yml, examples/openmm/metad/alanine-dipeptide.py, pysages/grids.py, pysages/methods/core.py, pysages/methods/metad.py
Revert to use `None` as fallback for grids in Metadynamics.
Fixes #151.
=> Fix empty grid construction in Metadynamics

docs/source/pysages_wordlist.txt, examples/openmm/abf/alanine-dipeptide_openmm.py, pysages/methods/abf.py, pysages/ml/objectives.py
Adding analyze for ABF, the function calculate the free energy from ABF simulation. It uses Sobolev approximation of functions by gradient learning, it requires a tuple with the topology for the net. The openmm example is updated accordingly.
=> Implement analyze for ABF

docs/source/pysages_wordlist.txt, pysages/colvars/coordinates.py
Something we discussed with @pabloferz and found that it may make for a more intuitive and flexible behavior for `Distance`.
Basically, we make the `Distance` CV a "barycenter distance" so that it can handle both distances between single points but also between group of points (by computing the distance between the barycenter aka center_of_geometry of the groups of atoms).
=> Make Distance a "COG Distance" (handles also groups of points)

examples/openmm/abf/alanine-dipeptide_openmm.py, examples/openmm/umbrella_integration/integration.py, pysages/methods/core.py, pysages/methods/ffs.py
Store the generated context into `context_args`.
This allows direct access to the simulation context in the `post_run_actions` to write final simulation files with OpenMM.
Hoomd-blue doesn't need it, since you can automatically operate on the currently activated context, but OpenMM seems to require direct access to the `simulation` object.
With the PR the following is possible for OpenMM.
```python
def post_run_action(**kwargs):
kwargs.get("context").saveState("final.xml")
```
The equivalent for hoomd-blue is:
```python
def post_run_action(**kwargs):
hoomd.dump.gsd(filename="final.gsd", overwrite=True, period=None, group=hoomd.group.all())
```
And it doesn't need direct access to the simulation context.
This makes restarting and keeping a checkpoint at the end possible.
=> Enable meaningful post action triggers for OpenMM

examples/hoomd-blue/ann/Butane_ANN.ipynb, examples/hoomd-blue/ann/Butane_ANN.md
Small (but still important, as it breaks the example) typo in the butane ANN example. 
[jupytext](https://github.com/mwouts/jupytext) is quite neat :)
=> Small fix in butane ANN example ipynb/md files

examples/hoomd-blue/funn/Butane_FUNN.ipynb, examples/hoomd-blue/funn/Butane_FUNN.md
The butane FUNN example was still using the `method.run` instead of `pysages.run` + `pysages.analyze`.
=> Update Butane-FUNN notebook to use the analyze function

.flake8, docs/source/pysages_wordlist.txt, pysages/methods/abf.py, pysages/methods/ann.py, pysages/methods/cff.py, pysages/methods/funn.py, pysages/methods/metad.py, pysages/methods/spectral_abf.py, pysages/methods/spline_string.py, pysages/methods/umbrella_integration.py, pysages/methods/utils.py
For the final result, we should prefer using normal numpy arrays instead of JAXarrays.
This should help a lot with pickling the final results.
JAX arrays can be a bit tricky to reconstruct in envs, that are not the same as the simulations were run.
So moving to numpy arrays, should enable user to pickle final results on the cluster and do the analysis (like plotting) on a local machine.
=> Use numpy numpy arrays in results, instead of JAX.numpy arrays

.github/workflows/ci.yml, Dockerfile, LICENSE.md, pysages/colvars/__init__.py, pysages/colvars/patterns.py, pysages/utils/__init__.py, pysages/utils/core.py, pysages/utils/transformations.py, tests/test_pickle.py
Accidentally closed #231. Reopening on top #240 (so tests pass).
Original PR description:
> Implementation of the Geometry Matching (GeM) Local Order Metric (LOM). The algorithm enabling the measurement of order in the neighborhood of an atomic or molecular site is described in [Martelli2018](https://journals.aps.org/prb/abstract/10.1103/PhysRevB.97.064105).
CC: @maggiezimon
=> Add GeM CV

.trunk/trunk.yaml
For #242 we had to bump the GH workflow files to test on python 3.8 instead of 3.7, but trunk merge requirements were not updated accordingly.
=> Update trunk merge checks to match the gh workflows

examples/Advanced_Sampling_Introduction.ipynb, examples/Advanced_Sampling_Introduction.md, examples/hoomd-blue/umbrella_integration/Umbrella_Integration.ipynb, examples/hoomd-blue/umbrella_integration/Umbrella_Integration.md
Curiously, there is a problem with the `plum.dispatch` of constructors.
If I specify arguments with keywords, a constructor is called that doesn't match any on the ones specified and I get basically an empty `UmbrellaIntegration` instance.
That is weird, and potentially problematic. But I don't know how to fix it.
Not using keywords in this case fixed the problem.
=> More fixes for the Google Collab notebooks

setup.cfg
Stopgap solution before #257 can be merged. This should allow people to use pysages while we sort out the issues with supporting plum 2.
=> Restrict plum to <2

.github/workflows/ci.yml, CONTRIBUTORS.md, Dockerfile, examples/lammps/unbiased/lj.lmp, examples/lammps/unbiased/unbiased.py, pysages/backends/core.py, pysages/backends/lammps.py, pysages/methods/core.py, pysages/ml/utils.py, pysages/utils/__init__.py, pysages/utils/compat.py, tests/test_pickle.py
Supersedes #110.
TODO:
In a separate follow up PR, we should integrate LAMMPS testing to our CI.
=> LAMMPS backend

pysages/utils/compat.py
This pr aims to fix the compatibility issue caused by `pysages/utils/compat.py`. During recent release 2.2.1, `plum` has dropped its support to Python 3.7, and removed functions and classes that were used as a workaround. As a result, I made edits to the scripts such that it will resort to Python's built-in `typing` module for `get_args()`, `get_origin()` and `Union`. These functions are introduced in Python 3.8, which is an install requirement of the latest `plum` module.
=> Fix compatibility issue with `plum >= 2.2.1`

docs/README.md, docs/source/_templates/layout.html, docs/source/conf.py, pysages/backends/hoomd.py, pysages/backends/lammps.py, pysages/backends/openmm.py, pysages/backends/utils.py, pysages/utils/compat.py
This PR addresses the following small but unrelated issues:
=> Miscellaneous fixes

pysages/methods/funn.py, pysages/methods/spectral_abf.py
In #292, we introduced a mechanism to count the number of calls to a method, but mistakenly that PR broke `SpectralABF` and `FUNN`, fixing those here.
In addition this makes the analysis for `SpectralABF` match the rest of the methods (it was giving the free energy surfaces with opposite sign to the rest of the methods).
=> Couple of fixes

Dockerfile, examples/hoomd3/restart/restart.py, examples/openmm/string/integration.py, pyproject.toml, pysages/__init__.py, pysages/serialization.py, setup.cfg, tests/test_pickle.py
This adds two new functions `pysages.save` and `pysages.load` that handle serialize+write to and read+deserialize from a file, respectively.
If a file was pickled before #292, `pysages.load` tries to workaround the fact that previous sampling method classes didn't contain a `ncalls` field.
Closes #298
=> Add functions for saving and loading simulation results

pysages/backends/ase.py
Storing the cell from an ASE MD environment currently will perform a transpose unintentionally. This error is usually harmless, but will cause problems when the cell is triclinic and restarting from a previous state. This pull request fixes this problem.
=> Fix incorrect ordering of the ase cell

.github/workflows/ci.yml, docs/requirements.txt, pysages/methods/core.py, pysages/utils/__init__.py, pysages/utils/compat.py
=> Compat option for jax devices

pysages/utils/compat.py
This pull request aims to fix the issue #323. A new signature fetching mechanism will be used whenever the `plum` version is greater than `2.3.0`.
=> Fix plum compatibility issue caused by 2.3.0 release

pysages/backends/utils.py, pysages/utils/__init__.py, pysages/utils/compat.py
With recent jax versions (`>0.4.27`) this causes errors when executing on CPUs.
=> [compat] Handle deprecation of jax.Array.device_buffer

pysages/ml/utils.py, pysages/utils/compat.py
This prevents `pysages` from being imported when `jax>=0.4.31`.
=> Compat option for `jax._src.core.canonicalize_shape`

pysages/backends/lammps.py
For LAMMPS, only unique masses are stored, instead the mass "type" of each particle is stored, and the mass of the `i`th particle can be retrieved as `masses[types][i]`. For this reason we store `(masses, types)` in place of a `masses`, this requires special handling when restoring which we missed initially. Fixing it here.
=> [lammps] Fix handling types when restoring
