SSAGESLabs/PySAGES

- pysages/backends/hoomd.py
This is needed as forces are computed asynchronously on the GPU.
> Ensure forces are synchronized before applying bias

- .gitignore
- pysages/__init__.py
and do not export version from it
> Add _version.py to gitignore

- pysages/backends/common.py
- pysages/backends/hoomd.py
- pysages/backends/openmm.py
- pysages/ssages/methods/abf.py
- pysages/ssages/methods/ann.py
- pysages/ssages/methods/funn.py
These helper functions (`indices`, `momenta`, `restore`) seem to start screaming for a dedicated data structure.
> Add method to restore snapshots

- pysages/backends/hoomd.py
- pysages/backends/openmm.py
- setup.cfg
The `from_dlpack` method now detects automatically the device.
> Update for jax 0.2.15

- pysages/backends/openmm.py
When on CPU make sure the inverse masses have the same shape as when on the GPU.
> More OpenMM on CPU fixes

- pysages/ssages/collective_variables/core.py
This dispatch fails with recent versions of plum.
> Fix building the CVs evaluation function

- Dockerfile
- pysages/backends/hoomd.py
This should fix some issues we are seeing when running with HOOMD-blue on GPUs.
> Update snapshot before method updating

- pysages/methods/core.py
- pysages/ml/__init__.py
- pysages/ml/models.py
- pysages/ml/objectives.py
- pysages/ml/optimizers.py
- pysages/ml/training.py
- pysages/ml/utils.py
- pysages/utils.py
This is a full rewrite of the `nn` submodule. The idea is to merge this in, then switch all the methods that use neural nets to use this instead and then to remove the previous submodule.
> New nn API

- README.md
- pysages/backends/hoomd.py
Works with the new hoomd-dlext implementation.
> New hoomd backend

- pysages/__init__.py
> Manually switch off XLA/GPU memory preallocation

- .github/workflows/docker-ci.yml
- examples/harmonic_bias/harmonic_bias.py
- examples/umbrella_integration/gen_gsd.py
- examples/umbrella_integration/integration.py
- pysages/methods/__init__.py
- pysages/methods/harmonic_bias.py
- pysages/methods/umbrella_integration.py
- pysages/methods/utils.py
simple/serial implementation for a start.
to be rebased later
> Implement umbrella integration

- pysages/utils.py
Make sure we are getting copies of `DeviceArray`s
> Fix copying of snapshots

- examples/abf/alanine-dipeptide_openmm.py
- examples/harmonic_bias/gen_gsd.py
- examples/harmonic_bias/harmonic_bias.py
- examples/umbrella_integration/gen_gsd.py
- pysages/backends/core.py
- pysages/backends/openmm.py
- pysages/methods/core.py
- pysages/ml/models.py
- pysages/ml/optimizers.py
- pysages/ml/utils.py
- pysages/nn/models.py
- pysages/nn/utils.py
- pysages/utils.py
These can be annoying for the user.
> Try handling current deprecations from jax and openmm

- pylintrc
- pysages/__init__.py
- pysages/approxfun/core.py
- pysages/backends/__init__.py
- pysages/backends/snapshot.py
- pysages/collective_variables/angles.py
- pysages/collective_variables/coordinates.py
- pysages/collective_variables/core.py
- pysages/collective_variables/shape.py
- pysages/grids.py
- pysages/ml/models.py
- pysages/ml/objectives.py
- pysages/ml/optimizers.py
- pysages/ml/training.py
- pysages/ml/utils.py
- pysages/utils.py
This came up as useful while working on #104
> Reorganize dispatch machinery

- examples/hoomd-blue/Harmonic_Bias.ipynb
- examples/hoomd-blue/Harmonic_Bias.md
- examples/hoomd-blue/Umbrella_Integration.ipynb
- examples/hoomd-blue/Umbrella_Integration.md
- examples/hoomd-blue/harmonic_bias/harmonic_bias.py
- examples/hoomd-blue/metad/butane.py
- examples/hoomd-blue/umbrella_integration/integration.py
- examples/openmm/Harmonic_Bias.ipynb
- examples/openmm/Harmonic_Bias.md
- examples/openmm/abf/alanine-dipeptide_openmm.py
- examples/openmm/forward_flux_sampling.py
- examples/openmm/metad/Metadynamics-ADP.ipynb
- examples/openmm/metad/Metadynamics-ADP.md
- examples/openmm/metad/alanine-dipeptide.py
- pysages/__init__.py
- pysages/methods/core.py
- pysages/methods/ffs.py
- pysages/methods/umbrella_integration.py
> Make `run` a module method instead of a class one

- .github/workflows/docker-ci.yml
- examples/hoomd-blue/Umbrella_Integration.ipynb
- examples/hoomd-blue/Umbrella_Integration.md
- examples/hoomd-blue/umbrella_integration/integration.py
- pysages/methods/umbrella_integration.py
- pysages/methods/utils.py
Factored out from #104 (rebase once #115 is merged).
> Use composition instead of inheritance for `UmbrellaIntegration`

- examples/openmm/metad/Metadynamics-ADP.ipynb
- examples/openmm/metad/Metadynamics-ADP.md
I was going through the metadynamics example and I noticed a couple of commands that seemed like belonging to a leftover cell (see changes). I removed them (not sure if we instead should change them to something else, in case I can update).
> MetaD example notebook fixes

- examples/hoomd-blue/Umbrella_Integration.ipynb
- examples/hoomd-blue/Umbrella_Integration.md
- examples/hoomd-blue/umbrella_integration/integration.py
- pysages/__init__.py
- pysages/methods/core.py
- pysages/methods/umbrella_integration.py
Factored out from https://github.com/SSAGESLabs/PySAGES/pull/104.
The idea is to eventually implement analyze functions for every sampling method so the user does not in general require knowledge about the details of each sampling method.
CC. @InnocentBug, @gustavor101, @sivadasetty, @ricalessandri, @ndtrung81
> Provide an `analyze` interface for post-run processing

- docs/source/module-pysages-methods-metad.rst
- docs/source/module-pysages-methods-utils.rst
- docs/source/module-pysages-methods.rst
- pysages/methods/metad.py
- pysages/methods/utils.py
There seems to be a problem with duplicate documenting bias.
But I don't understand the error message.
> add missing metad doc

- pysages/ml/objectives.py
I intended to add these during the ml rewrite. These are not being used yet, but are prep work for some of the methods missing such as SIRENs sampling.
> Add gradient-based objective functions

- pysages/grids.py
- pysages/methods/abf.py
- pysages/methods/ann.py
- pysages/methods/core.py
- pysages/methods/ffs.py
- pysages/methods/funn.py
- pysages/methods/harmonic_bias.py
- pysages/methods/metad.py
- tests/test_pickle.py
> Ensure all sampling methods are picklable

- pysages/backends/ase.py
- pysages/backends/core.py
Initial version of the backend. Needs a lot of testing with different ASE calculators to validate.
Fixes #49
> Support for ASE

- pysages/backends/hoomd.py
- pysages/backends/openmm.py
- pysages/backends/snapshot.py
- pysages/methods/ffs.py
This fixes the issue with FFS and HOOMD, but is also required for more easily supporting other backends such as ASE and jax-md.
> Make restore a sampler method

- .github/workflows/docker-ci.yml
- Dockerfile
- examples/ase/abf/water.py
- pysages/backends/ase.py
> Update ASE backend to support the latest restore API

- .github/workflows/docker-ci.yml
Hopefully this will fix the random failures when running with MPI in docker .
> Tweak docker-ci workflow

- .github/workflows/docker-ci.yml
- examples/openmm/spectral_abf/adp-vacuum.pdb
- examples/openmm/spectral_abf/alanine-dipeptide.py
Try using a symlink for the pdb file
> Tweak SpectralABF CI example

- examples/README.md
- examples/openmm/metad/Metadynamics-ADP.ipynb
- examples/openmm/metad/Metadynamics-ADP.md
Some links of recent (and less recent) addition to the OpenMM script example folder where missing links in the README file.
> Small fixes of the openmm examples

- examples/hoomd-blue/spectral_abf/butane_spectralABF.ipynb
- examples/hoomd-blue/spectral_abf/butane_spectralABF.py
python script in this first commit
> Add spectral ABF for butane example

- pysages/colvars/shape.py
> use eigh instead of eigvals

- pysages/backends/ase.py
- pysages/backends/hoomd.py
- pysages/backends/openmm.py
- pysages/methods/ffs.py
And use the interface in FFS.
Fixes #188.
> Add a take_snapshot method to backend Samplers

- pysages/backends/hoomd.py
For some reason the SystemView context manager was not always being exited. This seems to work and it should be safe as we are now returning copies of the arrays in `take_snapshot`.
As far as I can tell this fixes the segfault reported in #189 (both jax and hoomd-dlext were trying to free the arrays from the initial snapshot).
> Ensure that the context manager is exited

- pysages/backends/core.py
- pysages/backends/hoomd.py
These are the PySAGES-side changes needed to support HOOMD 3. This PR is to be merged after https://github.com/SSAGESLabs/hoomd-dlext/pull/15 gets merged.
> Add support for HOOMD 3

- examples/README.md
- examples/openmm/metad/nacl/Metadynamics_NaCl.ipynb
Add missing links to colab notebooks.
> Add ipynb links

- pysages/__init__.py
- pysages/backends/__init__.py
- pysages/backends/ase.py
- pysages/backends/core.py
- pysages/backends/hoomd.py
- pysages/backends/jax-md.py
- pysages/backends/openmm.py
- pysages/backends/snapshot.py
- pysages/methods/abf.py
- pysages/methods/ann.py
- pysages/methods/cff.py
- pysages/methods/ffs.py
- pysages/methods/funn.py
- pysages/methods/harmonic_bias.py
- pysages/methods/metad.py
- pysages/methods/spectral_abf.py
- pysages/methods/unbiased.py
Experimental support for jax-md as backend. Now that we have #190, jax-md would integrate more organically as backend.
Closes #109
cc: @sschoenholz
> Support jax-md as backend

- examples/hoomd-blue/ann/Butane_ANN.ipynb
- examples/hoomd-blue/ann/Butane_ANN.md
- examples/hoomd-blue/ann/butane_ann.py
- examples/hoomd-blue/cff/Butane_CFF.ipynb
- examples/hoomd-blue/cff/Butane_CFF.md
- pysages/methods/ann.py
- pysages/methods/cff.py
The cff analyze function should have the same output type (fes.max()-fes) as ABF and FUNN, this PR corrects this issue.
> CFF free energy results shifted to zero as ABF and FUNN

- pysages/methods/metad.py
In case of using grids, add restraints to metadynamics.
> Add restraints in metad.py for grids

- pysages/methods/cff.py
Add kT as input in method description
> Documentation for CFF

- .github/workflows/docker-ci.yml
- examples/openmm/metad/nacl/nacl-displacement.py
- examples/openmm/metad/nacl/nacl.py
This PR allows the use of the grids option in NaCl example using user args.
> Nacl example update

- pysages/methods/metad.py
calculate the correct grid_mesh in case of grids for metadynamics
> Fix grid scaling for MetaD

- pysages/methods/cff.py
- pysages/methods/funn.py
I fixed force calculation in analysis in cff.py and funn.py. The dimension of forces in the analysis was wrong (expansion is not needed).
> Fixed force calculation in analysis

- pysages/methods/abf.py
- pysages/methods/ann.py
- pysages/methods/cff.py
- pysages/methods/funn.py
- pysages/methods/spectral_abf.py
- pysages/ml/optimizers.py
- pysages/ml/utils.py
- pysages/utils.py
This should help with the issue found in #230.
PS. It also handles some recent jax deprecations.
> Fix some issues with ANN and CFF

- docs/source/module-pysages-colvars-angles.rst
- docs/source/pysages_wordlist.txt
- pysages/colvars/angles.py
Hi, I mainly fixed a few issues related to the documentation on the phase angle part:
1. added a few unrecognized words
2. fixing back quote issues
3. fixing a few inline latex issues so that it looks nicer.
> Fixing Ring CVs docs

- pysages/methods/core.py
Should help with #172. We might want to add tests for serializing parametric `Result` types (e.g. `Result[ANN]`)
> Make parametric Result types serializable

- .github/workflows/ci.yml
- .github/workflows/docker-base.yml
- .github/workflows/docker-ci.yml
- .github/workflows/docker.yml
Update most GH actions because of recent deprecations.
> Update GitHub Actions

- pysages/methods/abf.py
- pysages/methods/analysis.py
- pysages/methods/funn.py
- pysages/ml/models.py
- pysages/utils/__init__.py
- pysages/utils/core.py
I had missed removing the mean from the data before training the NN in both `analyze` implementations.
> Fix analyze for ABF and FUNN

- .github/workflows/ci.yml
- .trunk/.gitignore
- .trunk/config/cspell.config.yaml
- .trunk/trunk.yaml
- Dockerfile
- examples/hoomd-blue/harmonic_bias/Harmonic_Bias.ipynb
- examples/hoomd-blue/harmonic_bias/Harmonic_Bias.md
- examples/hoomd-blue/harmonic_bias/gen_gsd.py
- examples/hoomd-blue/string/gen_gsd.py
- examples/hoomd-blue/umbrella_integration/Umbrella_Integration.ipynb
- examples/hoomd-blue/umbrella_integration/Umbrella_Integration.md
- examples/hoomd-blue/umbrella_integration/gen_gsd.py
- examples/hoomd-blue/unbiased/gen_gsd.py
- examples/hoomd3/harmonic_bias/gen_gsd.py
- examples/hoomd3/string/gen_gsd.py
- examples/hoomd3/umbrella_integration/gen_gsd.py
- examples/hoomd3/unbiased/gen_gsd.py
- trunk
It's been a while since we last upgrade trunk.
> Upgrade trunk to 1.11 and CI fixes

- examples/README.md
Add the hoomd3 folder scripts to the description
> Update examples README.md

- README.md
- docs/requirements.txt
- docs/source/conf.py
- docs/source/index.md
- docs/source/installation.md
Update the readme file for the support for lammps and ase as backends.
> README update

- pysages/methods/__init__.py
- pysages/methods/ann.py
- pysages/methods/cff.py
- pysages/methods/sirens.py
- pysages/methods/spectral_abf.py
- pysages/ml/models.py
- pysages/ml/objectives.py
- pysages/ml/optimizers.py
- pysages/ml/utils.py
- tests/test_pickle.py
Implements the Sirens sampling method described in here https://arxiv.org/abs/2202.01876.
> Sirens sampling method

- pysages/ml/training.py
Fix issues for NN-based methods with larger number of CVs.
> Fix padding width
